"""empty message

Revision ID: 8421a527d5bf
Revises: d1f5a7318689
Create Date: 2020-05-03 01:45:11.987480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8421a527d5bf'
down_revision = 'd1f5a7318689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('refId', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('shippingAddress', sa.PickleType(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('space', sa.Column('farm_address', sa.PickleType(), nullable=True))
    op.add_column('space', sa.Column('logo', sa.String(length=50), nullable=True))
    op.add_column('space', sa.Column('suspended', sa.Boolean(), nullable=True))
    op.add_column('space', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('space', sa.Column('verified', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'space', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.drop_column('space', 'verified')
    op.drop_column('space', 'user_id')
    op.drop_column('space', 'suspended')
    op.drop_column('space', 'logo')
    op.drop_column('space', 'farm_address')
    op.drop_column('product', 'discount')
    op.drop_column('product', 'date_created')
    op.drop_table('review')
    op.drop_table('order')
    # ### end Alembic commands ###
