"""empty message

Revision ID: d1f5a7318689
Revises: 82929a12d3dc
Create Date: 2020-05-03 00:54:30.410649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f5a7318689'
down_revision = '82929a12d3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('Instock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'Instock')
    # ### end Alembic commands ###
